// Kernel.compute

#pragma kernel KernelRender

#include "Renderer.hlsl"
#include "Camera.hlsl"
#include "Ray.hlsl"
#include "Film.hlsl"

[numthreads(30,30,1)]
void KernelRender (uint3 id : SV_DispatchThreadID)
{
    uint2 screenIndex = id.xy;
    Ray ray = CameraGetSampleRay(screenIndex);
    float3 color = RayCasting(ray, screenIndex);
    SetFilmPixel(screenIndex, float4((float3) color, 1.0f));
}
