// Kernel.compute

#pragma kernel Clear
#pragma kernel Transform
#pragma kernel Render

#include "Rasterizer.hlsl"

[numthreads(32,18,1)]
void Clear(uint3 id : SV_DispatchThreadID)
{
    ClearPixel(id.xy);
}

[numthreads(512,1,1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    WorldToCameraTransform(id.x);
    CameraToNDCTransform(id.x);
}

[numthreads(32,18,1)]
void Render(uint3 id : SV_DispatchThreadID)
{
    RasterizeTriangle(id);
}
